# Generated by Django 2.0.1 on 2018-03-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trabajador',
            unique_together={('nombre', 'apellidos')},
        ),
    ]
