# Generated by Django 2.0.1 on 2018-03-23 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicionTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.Trabajador')),
            ],
            options={
                'db_table': 'ocurrencia_composicion_turno',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EntregaGuardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('elemento_entrega', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ocurrencia_entrega_guardia',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InstruccionRelevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('instruccion', models.TextField()),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.Trabajador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.Estado')),
            ],
            options={
                'db_table': 'ocurrencia_instruccion_relevo',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ocurrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('ocurrencia', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.Estado')),
                ('informado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.InformadoATpl')),
                ('reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.DepartamentoUoTpl')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TurnoGuardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('directivo_frente_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.Trabajador')),
                ('jefe_turno_mincom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe_turno_mincom', to='nomenclador.MincomPersonaTpl')),
                ('superior_mincom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior_mincom', to='nomenclador.MincomPersonaTpl')),
            ],
            options={
                'db_table': 'ocurrencia_turno_guardia',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ocurrencia',
            name='turno_guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocurrencia.TurnoGuardia'),
        ),
        migrations.AddField(
            model_name='entregaguardia',
            name='turno_guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocurrencia.TurnoGuardia'),
        ),
        migrations.AddField(
            model_name='composicionturno',
            name='turno_guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocurrencia.TurnoGuardia'),
        ),
    ]
