# Generated by Django 2.0.1 on 2018-03-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocurrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ocurrencia',
            table='ocurrencia',
        ),
    ]
