# Generated by Django 2.0.1 on 2018-05-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0002_auto_20180330_1615'),
        ('ocurrencia', '0002_auto_20180323_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcurrenciaInformadoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclador.InformadoATpl')),
                ('ocurrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocurrencia.Ocurrencia')),
            ],
            options={
                'db_table': 'ocurrencia_informado_a',
                'default_permissions': (),
            },
        ),
    ]
